// groupsIndexReducer
export const LOAD_GROUPS_INDEX = 'TOOL::LOAD_GROUPS_INDEX';
export const CLEAR_PREVIOUS_GROUPS_INDEX = 'TOOL::CLEAR_PREVIOUS_GROUPS_INDEX';
export const UPDATE_REFRESH_COUNT_GROUPS_INDEX = 'TOOL::UPDATE_REFRESH_COUNT_GROUPS_INDEX';
// contextIdReducer
export const CHANGE_CONTEXT_ID = 'TOOL::CHANGE_CONTEXT_ID';
export const CLEAR_CONTEXT_ID = 'TOOL::CLEAR_CONTEXT_ID';
// groupsDataReducer
export const CLEAR_PREVIOUS_GROUPS_DATA = 'TOOL::CLEAR_PREVIOUS_GROUPS_DATA';
export const LOAD_GROUPS_DATA_FROM_FS = 'TOOL::LOAD_GROUPS_DATA_FROM_FS';
export const TOGGLE_SELECTIONS_IN_GROUPDATA = 'TOOL::TOGGLE_SELECTIONS_IN_GROUPDATA';//TODO: VERIFY IF ITS FOUND IN REDUCER OPTIONS
export const SET_INVALIDATION_IN_GROUPDATA = 'TOOL::SET_INVALIDATION_IN_GROUPDATA';//TODO: VERIFY IF ITS FOUND IN REDUCER OPTIONS
// groupMenuReducer
export const GROUP_MENU_EXPAND_SUBMENU = 'TOOL::GROUP_MENU_EXPAND_SUBMENU';
export const TOGGLE_MENU_DRAWER = 'TOOL::TOGGLE_MENU_DRAWER';
export const GROUP_MENU_SET_FILTER = 'TOOL::GROUP_MENU_SET_FILTER';
export const CLEAR_PREVIOUS_FILTERS = 'TOOL::CLEAR_PREVIOUS_FILTERS';
// commentsReducer
export const ADD_COMMENT = 'TOOL::ADD_COMMENT';
// selectionsReducer
export const CHANGE_SELECTIONS = 'TOOL::CHANGE_SELECTIONS';
// bookmarksReducer
export const SET_BOOKMARK = 'TOOL::SET_BOOKMARK';
export const TOGGLE_BOOKMARK = 'TOOL::TOGGLE_BOOKMARK';
// verseEditReducer
export const ADD_VERSE_EDIT = 'TOOL::ADD_VERSE_EDIT';
// invalidatedReducer
export const SET_INVALIDATED = 'TOOL::SET_INVALIDATED';
export const SET_INVALIDATED_CHECKS_TOTAL = 'TOOL::SET_INVALIDATED_CHECKS_TOTAL';
export const SET_INVALIDATED_ALIGNMENTS_TOTAL = 'TOOL::SET_INVALIDATED_ALIGNMENTS_TOTAL';
export const SET_VERSE_EDITS_TOTAL = 'TOOL::SET_VERSE_EDITS_TOTAL';
