export const ADD_COMMENT = 'TOOL::ADD_COMMENT';
export const LOAD_GROUPS_INDEX = 'TOOL::LOAD_GROUPS_INDEX';
export const CLEAR_PREVIOUS_GROUPS_INDEX = 'TOOL::CLEAR_PREVIOUS_GROUPS_INDEX';
export const UPDATE_REFRESH_COUNT_GROUPS_INDEX = 'TOOL::UPDATE_REFRESH_COUNT_GROUPS_INDEX';
